### ISSUE TITLE
Create and get basic organizations datas

### ISSUE THREAD

**Issue by mateusoliveira2** [panelinhadees/client#5]
**Describe the solution you'd like**
Create a new page that gonna container the basic information's about the organization: *name*, *link to github*, *avatar* and *site*

Stay attend on the configuration that Nuxt make in the folders, I believe that this page stay on folder Page.

**Describe the solution you'd like**

![Screenshot from 2019-05-04 00-13-50](https://user-images.githubusercontent.com/6867958/57173162-c0317480-6e01-11e9-81dd-5a020ed7d5c9.png)

Page with centralized componentes with organization's info.

**Describe alternatives you've considered**
Each element is a componenet, avatar is a component, name other etc.

- [x] Create design

- [ ] Avatar

- [ ] Name

- [ ] Site

- [ ] Github

**Comment by thayannevls** [comment]
We need to design this page before implement.

We can do this week and put the design here

**Comment by thayannevls** [comment]
This issue is related to creating the components only, don't worry about how it's gonna receive this data etc
